DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS public.users(
	ID SERIAL NOT NULL UNIQUE,
	Username VARCHAR(127) NOT NULL UNIQUE,
	Password VARCHAR(127) NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS links;
CREATE TABLE IF NOT EXISTS public.links(
    ID SERIAL NOT NULL UNIQUE,
    Title VARCHAR (255) ,
    Address VARCHAR (255) ,
    UserID SERIAL ,
    CONSTRAINT links_pkey PRIMARY KEY (ID),
	CONSTRAINT links_user_fkey FOREIGN KEY (UserID) REFERENCES users(ID)
);